#!/bin/sh
# Author: Guillermo Robles
#
# Remove predetermined hooks, install the necessary ones

# Remove predetermined hooks
rm pre-commit.sample
rm prepare-commit-msg.sample

# Install the necessary ones
cp pre-commit ../.git/hooks/pre-commit
cp prepare-commit-msg ../.git/hooks/prepare-commit-msg
