#!/bin/sh
# Author: Guillermo Robles
#
# Inform the user of the TTF autocompilation

sed -i '1 a\\n# All the SFD files have been compiled into corresponding TTF files\n# Ignore the "not staged for commit" indicator\n#' "${1}"
