#!/bin/sh
# Author: Guillermo Robles
#
# Inform the user of the TTF autocompilation

if git status -v | grep -q '^diff --git a\/\(.*\)\.sfd b\/\1\.sfd$'; then
    sed -i '1 a\\n# All the SFD files have been compiled into corresponding TTF files\n# Ignore the "not staged for commit" indicator\n#' "${1}"
fi
